### ISSUE TITLE
config.toml:16: Replace discuss which has now been...

### ISSUE THREAD

**Issue by 0pdd** [bryanapperson/blog#19]
The puzzle `1-ecc1d8cd` from #1 has to be resolved: 

https://github.com/bryanapperson/blog/blob/33a08454e53b8821109458ff00590c381acc7e75/config.toml#L16-L16

The puzzle was created by Bryan Apperson on 04-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bryanapperson** [comment]
https://gohugohq.com/howto/staticman-hugo-comment-system/

**Comment by 0pdd** [comment]
The puzzle `1-ecc1d8cd` has disappeared from the source code, that's why I closed this issue.
